### ISSUE TITLE
Agrometeorology packages

### ISSUE THREAD

**Issue by adriancorrendo** [cran-task-views/Agriculture#83]
Hi there @adamhsparks , @jpiaskowski 

I just realized there are a few packages/APIs related to accessing weather data that are worth it (I think) to be included as part of the "Agrometeorology" section of this CTV.

These packages are:
- [nasapower: Nasapower API Client](https://cran.r-project.org/package=nasapower)
- [daymetr: Interface to the 'Daymet' Web services](https://cran.r-project.org/package=daymetr)
- [chirps: API Client for CHIRPS and CHIRTS](https://cran.r-project.org/package=chirps)

I use them myself, and used them for publishing a code to use these APIs (https://github.com/adriancorrendo/AgrometR, https://doi.org/10.1186/s13104-021-05622-8)

Also, Adam, I've checked on this other one based on one of your linkedin posts...but I haven't used it. Do you think this ctv would be appropriate? I believe so, but I'd like your opinion being the developer.
- [GSODR: Global Surface Summary of the Day ('GSOD') Weather Data Client] (https://cran.r-project.org/package=GSODR)

Thanks,
Adrian

**Comment by adamhsparks** [comment]
Hi @adriancorrendo, I haven't added {nasapower}, {chirps} or {GSODR} partly because I've written or contributed to them and I may just be being modest but they're already in hydrology CTVs. But I certainly have written them with agrometeorology in mind. In fact, {GSODR} has the capability to fetch only station data between -60 --  60 latitude for global agrometeorology work.

I don't really have a clear handle on the CRAN or CTV policies where packages have a good bit of overlap between CTVs, TBH, @jpiaskowski do you have any thoughts?

**Comment by jpiaskowski** [comment]
We did [discuss this previously](https://github.com/cran-task-views/Agriculture/issues/26). The concern was that this task view was getting a bit too broad. If I recall, the thinking was to have genera weather retrieval packages in the hydrology TV and only include agrometeorology packages in the Agriculture TV is the package did additional data transformation that was useful to ag audiences. We don't want to have to track all weather retrieval packages.

**Comment by adamhsparks** [comment]
Thanks, @jpiaskowski, that's why I had that idea about the specificity apparently. Short memory. 😆

**Comment by adriancorrendo** [comment]
Thank you very much for the explanation. 

No changes then on the agrometeorology section of the CTV.

Cheers,
Adrian
